export const ALL_CURATED_DESTINATIONS = [
  // ================= INDIA (HERITAGE, LAKES, COASTAL, SPIRITUAL, HIMALAYAS) =================
  {
    id: 101,
    name: 'Jaipur (Pink City)',
    country: 'India',
    continent: 'Asia',
    description: 'The royal capital of Rajasthan famous for Amber Fort, Hawa Mahal Palace of Winds, and vibrant Johari gem bazaars.',
    image_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 60,
    currency: 'INR',
    popularity_score: 98,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'The Raj Palace Heritage Grand Haveli / Rambagh Palace',
    best_food: 'Dal Baati Churma at Chokhi Dhani, Rawat Pyaaz Kachori & Ghewar',
    top_sights: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar']
  },
  {
    id: 102,
    name: 'Udaipur (City of Lakes)',
    country: 'India',
    continent: 'Asia',
    description: 'Romantic white marble palaces mirrored on Lake Pichola, royal courtyards, and sunset boat safaris.',
    image_url: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 75,
    currency: 'INR',
    popularity_score: 97,
    best_time_to_visit: 'Sep - Mar',
    best_hotel: 'Taj Lake Palace on Lake Pichola / The Oberoi Udaivilas',
    best_food: 'Lakeside Rajasthani Thali at Ambrai & Gatte Ki Sabzi',
    top_sights: ['Lake Pichola Boat Cruise', 'City Palace Museum', 'Jag Mandir', 'Saheliyon Ki Bari']
  },
  {
    id: 103,
    name: 'Agra (Taj Mahal Heritage)',
    country: 'India',
    continent: 'Asia',
    description: 'Home of the sublime Taj Mahal, UNESCO Red Fort, and historic Mughal artisan stonecraft.',
    image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 55,
    currency: 'INR',
    popularity_score: 99,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'The Oberoi Amarvilas (Direct Taj Views) / ITC Mughal',
    best_food: 'Authentic Mughlai Biryani, Bedmi Puri & Agra Panchhi Petha',
    top_sights: ['Taj Mahal Sunrise Tour', 'Agra Fort', 'Mehtab Bagh Sunset', 'Fatehpur Sikri']
  },
  {
    id: 104,
    name: 'Delhi (Capital City)',
    country: 'India',
    continent: 'Asia',
    description: 'A 2,000-year-old historic metropolis blending Mughal grand monuments with cutting-edge culinary culture.',
    image_url: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 65,
    currency: 'INR',
    popularity_score: 96,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'The Imperial New Delhi / The Leela Palace Chanakyapuri',
    best_food: 'Old Delhi Karim\'s Kebabs, Chandni Chowk Paranthas & Butter Chicken',
    top_sights: ['Qutub Minar', 'Humayun\'s Tomb', 'Red Fort', 'India Gate Promenade']
  },
  {
    id: 105,
    name: 'Goa (Tropical Coast)',
    country: 'India',
    continent: 'Asia',
    description: 'Golden sand beaches, Portuguese colonial cathedrals, waterfall superjeep treks, and beach shack seafood.',
    image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 80,
    currency: 'INR',
    popularity_score: 98,
    best_time_to_visit: 'Nov - Apr',
    best_hotel: 'Taj Exotica Resort & Spa Benaulim / W Goa Vagator',
    best_food: 'Goan Prawn Balchão, Fish Recheado at Martin\'s Corner & Bebinca',
    top_sights: ['Dudhsagar Glacial Waterfall', 'Basilica of Bom Jesus', 'Palolem Beach', 'Fort Aguada']
  },
  {
    id: 106,
    name: 'Kerala (Munnar & Alleppey)',
    country: 'India',
    continent: 'Asia',
    description: 'God\'s Own Country: tranquil private houseboat backwater lagoons, mist-clad Munnar tea hills, and Kathakali theatre.',
    image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 70,
    currency: 'INR',
    popularity_score: 97,
    best_time_to_visit: 'Sep - Mar',
    best_hotel: 'Kumarakom Lake Resort / Luxury Private Backwater Houseboat',
    best_food: 'Karimeen Pollichathu, Kerala Banana Leaf Sadya & Appam with Stew',
    top_sights: ['Alleppey Houseboat Cruise', 'Munnar Tea Gardens', 'Fort Kochi Chinese Fishing Nets']
  },
  {
    id: 107,
    name: 'Varanasi (Spiritual Capital)',
    country: 'India',
    continent: 'Asia',
    description: 'One of the world\'s oldest living cities on the sacred River Ganga, famous for the magical Dashashwamedh Ghat Aarti.',
    image_url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 45,
    currency: 'INR',
    popularity_score: 95,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'BrijRama Palace on Darbhanga Ghat / Taj Ganges',
    best_food: 'Banarasi Tamatar Chaat, Deena Kachori Jalebi, Malaiyyo & Kashi Paan',
    top_sights: ['Dashashwamedh Ghat Evening Aarti', 'Ganga Sunrise Boat', 'Kashi Vishwanath Corridor']
  },
  {
    id: 108,
    name: 'Kashmir (Srinagar & Gulmarg)',
    country: 'India',
    continent: 'Asia',
    description: 'Paradise on Earth: Dal Lake floating flower markets, Shikara wooden houseboats, and Gulmarg alpine snow peaks.',
    image_url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 75,
    currency: 'INR',
    popularity_score: 96,
    best_time_to_visit: 'Apr - Oct (Snow: Dec - Feb)',
    best_hotel: 'The Khyber Himalayan Resort & Spa Gulmarg / Luxury Dal Lake Shikara Houseboat',
    best_food: 'Traditional Kashmiri Wazwan (Rogan Josh, Gushtaba) & Saffron Kahwa',
    top_sights: ['Dal Lake Shikara Cruise', 'Gulmarg Gondola Cable Car', 'Pahalgam Betaab Valley']
  },
  {
    id: 109,
    name: 'Manali & Himachal',
    country: 'India',
    continent: 'Asia',
    description: 'Pine-scented mountain valleys, Rohtang Pass glacial viewpoints, paragliding over Solang, and hot springs.',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 60,
    currency: 'INR',
    popularity_score: 94,
    best_time_to_visit: 'Mar - Jun & Oct - Feb',
    best_hotel: 'The Himalayan Luxury Resort & Spa / Span Resort & Spa',
    best_food: 'Himachali Siddu with Pure Ghee, Trout Fish & Old Manali Momos',
    top_sights: ['Rohtang Pass Snow View', 'Solang Valley Paragliding', 'Hidimba Temple']
  },
  {
    id: 110,
    name: 'Rishikesh (Yoga Capital)',
    country: 'India',
    continent: 'Asia',
    description: 'Spiritual Himalayan haven with world-class white water rafting on the holy Ganga and ancient meditation ashrams.',
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 50,
    currency: 'INR',
    popularity_score: 93,
    best_time_to_visit: 'Sep - May',
    best_hotel: 'Ananda in the Himalayas / Aloha On The Ganges',
    best_food: 'Chotiwala Authentic Satvik Thali & Beatles Cafe Organic Smoothies',
    top_sights: ['Ganga White Water Rafting', 'Beatles Ashram Sanctuary', 'Triveni Ghat Evening Aarti']
  },
  {
    id: 111,
    name: 'Mumbai (Maximum City)',
    country: 'India',
    continent: 'Asia',
    description: 'India\'s economic heartbeat: Gateway of India, Marine Drive Queen\'s Necklace, Art Deco promenades, and street food.',
    image_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    cost_index: 'luxury',
    avg_daily_cost: 95,
    currency: 'INR',
    popularity_score: 96,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'The Taj Mahal Palace Mumbai (Historic Heritage Wing)',
    best_food: 'Mumbai Vada Pav, Sardar Pav Bhaji, Britannia Berry Pulao & Irani Chai',
    top_sights: ['Gateway of India', 'Marine Drive Sunset', 'Elephanta Caves Ferry', 'Bandra Seaface']
  },
  {
    id: 112,
    name: 'Jodhpur (Blue City)',
    country: 'India',
    continent: 'Asia',
    description: 'Sun-drenched blue houses crowned by the mighty Mehrangarh Fort towering above the Thar desert sands.',
    image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    cost_index: 'budget',
    avg_daily_cost: 50,
    currency: 'INR',
    popularity_score: 92,
    best_time_to_visit: 'Oct - Mar',
    best_hotel: 'Umaid Bhawan Palace / RAAS Jodhpur Luxury Heritage',
    best_food: 'Jodhpuri Shahi Mirchi Vada, Mawa Kachori & Ker Sangri',
    top_sights: ['Mehrangarh Fort Ramparts', 'Jaswant Thada Royal Cenotaphs', 'Blue City Alleys']
  },

  // ================= GLOBAL DESTINATIONS (IDs 201+) =================
  {
    id: 201,
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    description: 'Futuristic neon skyline, serene Shinto shrines, Michelin-starred cuisine, and digital art sanctuaries.',
    image_url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 140,
    currency: 'JPY',
    popularity_score: 99,
    best_time_to_visit: 'Mar - May & Sep - Nov',
    best_hotel: 'Cerulean Tower Tokyu Hotel / Aman Tokyo',
    best_food: 'Tsukiji Fresh Otoro Sashimi & Wagyu Sukiyaki',
    top_sights: ['Shibuya Sky', 'TeamLab Planets', 'Tsukiji Outer Market', 'Senso-ji']
  },
  {
    id: 202,
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    description: 'Historic cultural capital of Japan with 10,000 Torii gates, zen rock gardens, and traditional Gion geisha districts.',
    image_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 125,
    currency: 'JPY',
    popularity_score: 98,
    best_time_to_visit: 'Mar - May & Oct - Nov',
    best_hotel: 'Kyoto Gion Machiya Heritage Suites / Hoshinoya Kyoto',
    best_food: 'Gion Ceremonial Matcha & Pontocho Kaiseki Feast',
    top_sights: ['Fushimi Inari Torii Gates', 'Arashiyama Bamboo Forest', 'Kinkaku-ji']
  },
  {
    id: 203,
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    description: 'The City of Light: iconic Eiffel Tower, world-class Louvre art masterworks, and Seine riverboat gastronomy.',
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    cost_index: 'luxury',
    avg_daily_cost: 185,
    currency: 'EUR',
    popularity_score: 99,
    best_time_to_visit: 'Apr - Jun & Sep - Nov',
    best_hotel: 'Boutique Designer Loft in Le Marais / Ritz Paris',
    best_food: 'Duck Confit in Saint-Germain & French Wine Tasting',
    top_sights: ['Louvre Museum', 'Eiffel Tower Summit', 'Seine River Dinner Cruise']
  },
  {
    id: 204,
    name: 'Zermatt (Matterhorn)',
    country: 'Switzerland',
    continent: 'Europe',
    description: 'Car-free fairytale alpine village at the foot of the iconic pyramid peak of the Matterhorn.',
    image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80',
    cost_index: 'luxury',
    avg_daily_cost: 220,
    currency: 'CHF',
    popularity_score: 97,
    best_time_to_visit: 'Jun - Sep & Dec - Apr',
    best_hotel: 'Mont Cervin Palace Zermatt / Omnia Chalet',
    best_food: 'Valais Fondue & Fendant Alpine White Wine',
    top_sights: ['Gornergrat Cogwheel Rail', 'Matterhorn Glacier Paradise']
  },
  {
    id: 205,
    name: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    description: 'The Eternal City: ancient Colosseum gladiator arena, Vatican Sistine Chapel, and baroque gelato piazzas.',
    image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    cost_index: 'moderate',
    avg_daily_cost: 135,
    currency: 'EUR',
    popularity_score: 98,
    best_time_to_visit: 'Apr - Jun & Sep - Oct',
    best_hotel: 'Palazzo Navona Hotel Rome / Hotel de Russie',
    best_food: 'Classic Roman Cacio e Pepe, Carbonara & Gelato',
    top_sights: ['Colosseum & Forum', 'Vatican & Sistine Chapel', 'Trevi Fountain']
  },
  {
    id: 206,
    name: 'New York City',
    country: 'United States',
    continent: 'North America',
    description: 'High Line gardens, Summit One Vanderbilt glass skyboxes, Broadway shows, and Central Park.',
    image_url: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    cost_index: 'luxury',
    avg_daily_cost: 230,
    currency: 'USD',
    popularity_score: 99,
    best_time_to_visit: 'Sep - Nov & Apr - Jun',
    best_hotel: 'The Plaza Hotel / The Standard High Line',
    best_food: 'New York Style Pastrami & Chelsea Market Eats',
    top_sights: ['Summit One Vanderbilt', 'High Line', 'Central Park', 'Broadway']
  },
  {
    id: 207,
    name: 'Reykjavik',
    country: 'Iceland',
    continent: 'Europe',
    description: 'Geothermal Blue Lagoon mineral soaks, roaring Gullfoss waterfalls, and celestial Northern Lights.',
    image_url: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=800&q=80',
    cost_index: 'luxury',
    avg_daily_cost: 190,
    currency: 'ISK',
    popularity_score: 96,
    best_time_to_visit: 'Sep - Mar (Aurora) & Jun - Aug',
    best_hotel: 'The Retreat at Blue Lagoon / ION Adventure Hotel',
    best_food: 'Smoked Arctic Char, Fresh Salmon & Skyr',
    top_sights: ['Blue Lagoon Geothermal Soak', 'Golden Circle', 'Northern Lights Hunt']
  }
];
